#!/bin/sh
picom &
slstatus &
# More reliable check for secondary monitor
if xrandr | grep "eDP-1-1 connected"; then
  # Execute script without background process
  /home/mawsis/suckless/secondMonitor
else
  feh --bg-fill /home/mawsis/suckless/mountainsPurple.png &
fi
dwm
